### ISSUE TITLE
Document key values

### ISSUE THREAD

**Issue by DanKaplanSES** [RobertWHurst/Keystrokes#1]
**Is your feature request related to a problem? Please describe.**
I had to read the source code to figure out what values I could pass in for the `key`.

**Describe the solution you'd like**
I would like the documentation to link to https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values This lists all possible `key` values.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by RobertWHurst** [comment]
There is a link to [https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values](that MDN page) under the section [https://github.com/RobertWHurst/Keystrokes#binding-keys-and-key-combos](Binding Keys and Key Combos) in the readme. Perhaps I'll make this more prominent in the readme.

**Comment by RobertWHurst** [comment]
I've updated the readme to better highlight the link to the MDN page.
