### ISSUE TITLE
`keyRemap` option is not being applied

### ISSUE THREAD

**Issue by DarkLight1337** [RobertWHurst/Keystrokes#15]
**Description**
When setting the options of `Keystrokes` (whether in the constructor or through `bindEnvironment()`), `keyRemap` fails to be applied.

**Reproducible Example**
```js
const keystrokes = new Keystrokes({
    keyRemap: { ' ': 'space' },
});

// No message is logged when pressing spacebar
keystrokes.bindKeyCombo('space', console.log);
```

**Temporary Workaround**
Directly setting the private attribute `_keyRemap` seems to fix the issue:

```js
const keystrokes = new Keystrokes();

// @ts-expect-error
keystrokes._keyRemap = { ' ': 'space' };

// This now works
keystrokes.bindKeyCombo('space', console.log);
```

**Comment by RobertWHurst** [comment]
Here Darklight. Thanks for reporting this. I'll take a look tomorrow morning.

**Comment by RobertWHurst** [comment]
Hey @DarkLight1337, thanks for the report. I had a look and indeed I missed the assignment of the remap. I've issued a fix and added a test. I've also just issued the v1.1.2 release and it should resolve the issue for you. Let me know if you continue to run into any issues.

**Comment by DarkLight1337** [comment]
Can confirm it got fixed, thanks!
