### ISSUE TITLE
Cancel key combo when switching to a different window

### ISSUE THREAD

**Issue by DarkLight1337** [RobertWHurst/Keystrokes#16]
When I switch to a different window via keyboard (e.g. <kbd>Alt+Tab</kbd>), then return to the original window without using the keyboard (e.g. via clicking on it), the active key combo becomes stuck at the state before I left the window (e.g. at <kbd>Alt</kbd>), until I press and release the key again. This behaviour may confuse users into thinking that the key combos have stopped working.

It would be great if the active key combo automatically cancels when the window loses focus.

Here is a temporary solution that seems to work on keyboard shortcuts for tabbing out of the active window (I only tested on Windows though):

```js
const keystrokes = new Keystrokes({
    selfReleasingKeys: [
        'ctrl', 'meta', 'alt', 'tab',
    ],
    keyRemap: {
        control: 'ctrl',
        os: 'meta',     // For Firefox
    },
});

addEventListener('blur', () => {
    // Prevent getting stuck in a key sequence after tabbing to a different window
    // @ts-expect-error
    keystrokes._tryReleaseSelfReleasingKeys();
});

```

**Comment by RobertWHurst** [comment]
Yes, I had added this back with KeyboardJS. I'm trying to decide if this should go in the browser bindings, or in the library; I'm trying to decide if this is a platform dependent behavior or a general one.

**Comment by RobertWHurst** [comment]
Just put out a new release with this behavior added.

**Comment by DarkLight1337** [comment]
I've played around a bit and it seems to work as intended. Thanks!
