### ISSUE TITLE
Failed to resolve entry for package "@rwh/vue-keystrokes"

### ISSUE THREAD

**Issue by george-martinec** [RobertWHurst/Keystrokes#17]
**Describe the bug**
```Failed to resolve entry for package "@rwh/vue-keystrokes". The package may have incorrect main/module/exports specified in its package.json.```

**To Reproduce**
1. Install

**Expected behavior**

**Additional context**

![1](https://github.com/RobertWHurst/Keystrokes/assets/87377447/b8508c81-fb83-4099-919d-83650789e977)
![2](https://github.com/RobertWHurst/Keystrokes/assets/87377447/5b13ffc5-4d49-4327-9803-43ae73d7f182)

**Comment by RobertWHurst** [comment]
Thanks for pointing this out. I must have broke this when I moved from parcel to vite. I'll get a fix out in the next hour or so.

**Comment by RobertWHurst** [comment]
Yikes! I must have did this when I replaced parcel with vite. I should have did some external testing. Thank you for reporting this. I've fixed the name of the file in the build dist folder. Let me know if you run into any other issues. I've published the fix under v1.1.4.

**Comment by RobertWHurst** [comment]
Going to close for now. If you have any other issues we can re-open.
