### ISSUE TITLE
originalEvent.composedPath() return empty array

### ISSUE THREAD

**Issue by Senasiko** [RobertWHurst/Keystrokes#2]
**Describe the bug**
when use `composedPath` in `bindKeyCombo` callback, return empty array.
```
bindKeyCombo('Meta + z', (e) => {
    const path = e.originalEvent.composedPath(); // path is []
});
```
The issue seems to be that callback exec in next micro task 
https://stackoverflow.com/questions/62181537/why-does-composedpath-on-event-returns-different-value-when-delayed

**Expected behavior**
return true array

**Additional context**

**Comment by RobertWHurst** [comment]
I'll have a look at this today. Out of curiosity, what are you using the method for?

**Comment by RobertWHurst** [comment]
@Senasiko have a look at #3 if you wish. I'll be adding a test case to verify the fix as well as test the new mapper function before it's merged. Given that you have looked through the code, and that this PR should fix your use case I'd be interested in your thoughts.

**Comment by RobertWHurst** [comment]
Ok, I've added a few tests and fixed a bug. Next is updating the docs. I'll take a pass at that tonight, then I should be able to roll out a release shortly after that.

**Comment by RobertWHurst** [comment]
Sorry that took so long. The latest release has your composedPath now.
