### ISSUE TITLE
Unable to type Shift + "+" combination

### ISSUE THREAD

**Issue by terminal29** [RobertWHurst/Keystrokes#27]
**Describe the bug**
I'm unable to bind a key combination of "Shift + +" with error `cannot have two operators in a row`

**To Reproduce**
1. Call bindKeyCombo("Shift + +")
2. Throws

**Expected behavior**
The lib recognises a + followed by a + means to bind every second + in a sequence as a key instead of an operator. It should probably do the same with combinations involving `>` and `,` keys too so you can have combinations like "Shift + , , , + Shift".

**Additional context**
Might be also be useful to have some sort of opt-in to use a keys `.code` instead of just `.key` because as far as i can see, it's impossible to specify specific keys like ShiftLeft for eg.

**Comment by RobertWHurst** [comment]
Hi @terminal29, this is something currently missing from the Readme, I'm glad you asked. I'll have to update it to mention this.

So for characters that are the same as operators that Keystrokes uses, you can actually escape them with backslash.

For your combo try `bindKeyCombo("Shift + \\+")`.

Going to keep this ticket open until I've updated the readme.

**Comment by RobertWHurst** [comment]
Ok, I've added some language around how combo operators and escaping work. Glad to have that in there now. Thanks for the report. I'm going to close this, but let me know if you have any further issues.
