### ISSUE TITLE
Unable to import Keystrokes class

### ISSUE THREAD

**Issue by DarkLight1337** [RobertWHurst/Keystrokes#28]
### Describe the bug
The `Keystrokes` class is no longer exported in the `index.ts` file, preventing the creation of [custom instances](https://github.com/RobertWHurst/Keystrokes#creating-instances).

### Additional context
I assume this was unintentional since it's still being referenced in the docs.

**Comment by RobertWHurst** [comment]
Thanks for reporting this. I went through and reviewed the exports. Pretty much everything that could be useful should be exported now as of v1.3.1. Sorry for the inconvenience.
