### ISSUE TITLE
`useKeyCombo` from `@rwh/react-keystrokes` does not work in version 1.5.*

### ISSUE THREAD

**Issue by Bernankez** [RobertWHurst/Keystrokes#35]
**Describe the bug**
`useKeyCombo` does not work in version 1.5.*, but works in 1.3.1

**To Reproduce**
version 1.5.1 [reproduction](https://codesandbox.io/p/sandbox/beautiful-surf-9jmk3g?file=%2Fsrc%2FApp.js%3A12%2C55&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqdgh4p200063p6kgonypbbi%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqdgh4p100023p6k1b8thpx1%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqdgh4p100033p6kds63gz3c%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqdgh4p100053p6ksdrij53i%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqdgh4p100023p6k1b8thpx1%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqdgh4p100013p6kvwkguumx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clqdgy6ec00a73p6kzw937j82%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A55%252C%2522endLineNumber%2522%253A12%252C%2522endColumn%2522%253A55%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqdgh4p100023p6k1b8thpx1%2522%252C%2522activeTabId%2522%253A%2522clqdgy6ec00a73p6kzw937j82%2522%257D%252C%2522clqdgh4p100053p6ksdrij53i%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqdgh4p100043p6k1h7444dx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqdgh4p100053p6ksdrij53i%2522%252C%2522activeTabId%2522%253A%2522clqdgh4p100043p6k1h7444dx%2522%257D%252C%2522clqdgh4p100033p6kds63gz3c%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqdgh4p100033p6kds63gz3c%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

version 1.3.1 [reproduction](https://codesandbox.io/p/sandbox/beautiful-surf-forked-kr2h3m?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqdgh4p200063p6kgonypbbi%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqdgh4p100023p6k1b8thpx1%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqdgh4p100033p6kds63gz3c%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqdgh4p100053p6ksdrij53i%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqdgh4p100023p6k1b8thpx1%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqdgh4p100013p6kvwkguumx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clqdgy6ec00a73p6kzw937j82%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A55%252C%2522endLineNumber%2522%253A12%252C%2522endColumn%2522%253A55%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqdgh4p100023p6k1b8thpx1%2522%252C%2522activeTabId%2522%253A%2522clqdgy6ec00a73p6kzw937j82%2522%257D%252C%2522clqdgh4p100053p6ksdrij53i%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqdgh4p100043p6k1h7444dx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqdgh4p100053p6ksdrij53i%2522%252C%2522activeTabId%2522%253A%2522clqdgh4p100043p6k1h7444dx%2522%257D%252C%2522clqdgh4p100033p6kds63gz3c%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqdgh4p100033p6kds63gz3c%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Expected behavior**

**Additional context**

**Comment by Bernankez** [comment]
https://github.com/RobertWHurst/Keystrokes/blob/f9af78cc9e6dd86785016b46f6c4b2dee496c7e0/packages/keystrokes/src/key-combo-state.ts#L271
It seems to be here. When `activeKeyPresses.length` is greater than `unit.length` (for example, `activeKeyPresses` is `["a", "@keya", "b", "@keyb"]`, and `unit` is `["a", "z"]`, the `activeKeyIndex` is `0`), at this time `activeKeyPresses` is not fully iterated, resulting in the key not being found.

**Comment by RobertWHurst** [comment]
Looks like I need to update the tests to handle this case as well. Somehow it was missed. Thanks for reporting. A fix is on it's way.

**Comment by RobertWHurst** [comment]
@Bernankez Ok I've released 1.5.4 which resolves the issue. Again thanks for raising this issue 🍻.
