### ISSUE TITLE
Cannot use key aliases with bindKey or checkKey

### ISSUE THREAD

**Issue by se-panfilov** [RobertWHurst/Keystrokes#38]
Hope I'm note doing things wrong, but it looks like that key codes functionality ([issue#33](https://github.com/RobertWHurst/Keystrokes/issues/33)) is broken at least at v1.5.4

```
bindKey("a", () => console.log("a key")); //working
bindKey("@KeyW", () => console.log("w code")); //doesn't work
```

codesandbox: https://codesandbox.io/p/sandbox/keystroke-codes-issue-3n9nny

P.S. with 1.5.0 it's working, but I didn't make it work with numpad, e.g. `bindKey("@KeyNumpad4", () => console.log("4 code"))`

**Comment by RobertWHurst** [comment]
Hi @se-panfilov. I took a closer look. Key aliases are working for bindKeyCombo, but you are correct - they are not working with bindKey or checkKey. Thanks for reporting the issue, it's greatly apreciated.

I've deployed a fixed version (v1.5.5)

Let me know if you run into further issues.
