### ISSUE TITLE
Arrow keys not detected with checkKey

### ISSUE THREAD

**Issue by Elliot67** [RobertWHurst/Keystrokes#40]
Arrow keys are not detected in `checkKey` , but they are properly detected with `bindKey`.
Using `checkKeyCombo` works fine.

Made a [reproduction on jsfiddle](https://jsfiddle.net/peftwr32/) with the following code :
```ts
import * as rwhkeystrokes from 'https://esm.run/@rwh/keystrokes';

rwhkeystrokes.bindKey('a', () => console.log('bind a'))
rwhkeystrokes.bindKey('ArrowRight', () => console.log('bind ArrowRight'))

const int = window.setInterval(() => {
  if (rwhkeystrokes.checkKey('a')) {
    console.log('a is pressed')
  }
  
  
  if (rwhkeystrokes.checkKey('ArrowRight')) {
  //if (rwhkeystrokes.checkKeyCombo('ArrowRight')) {
    console.log('ArrowRight is pressed')
  }
}, 100)
```

**Comment by RobertWHurst** [comment]
Indeed. The library is case insensitive (or at least it's suppose to be), and yet here checkKey is not properly normalizing the input. It works if you pass `'arrowright'`. I'll get a new version with a fix published today. Thanks for reporting this bug 👍🏻
