### ISSUE TITLE
Bug with self releasing keys feature

### ISSUE THREAD

**Issue by colinsullivan** [RobertWHurst/Keystrokes#7]
**Describe the bug**
Crash when using self-releasing keys feature

**To Reproduce**
Use self-releasing keys with a key combo
Note error in console

**Expected behavior**
Feature works

**Additional context**

The issue is here:

https://github.com/RobertWHurst/Keystrokes/blob/master/packages/keystrokes/src/keystrokes.ts#L435

Note the objects in `_activeKeyPresses` are already in the form of `{ key: "z", event: { ... } }`.  Then the crash occurs here:

https://github.com/RobertWHurst/Keystrokes/blob/master/packages/keystrokes/src/keystrokes.ts#L340

Because `event.key.toLowerCase` is undefined

**Comment by colinsullivan** [comment]
Got a test , not sure how to fix it though...

The `_tryReleaseSelfReleasingKeys` method seems like it has additional problems, maybe the feature hasn't been worked through fully yet?

**Comment by RobertWHurst** [comment]
Thanks for reporting this issue. Let me take a look at your PRs.
🍻

**Comment by RobertWHurst** [comment]
Closing as I've merged #10 but we can continue the conversation if you have feedback.
